Develop (#3)
* Feature/build docker (#2)

* make onnx module

* need to fix undefined reference to modules

* make file and docker works but image isnt finding the onnxruntime

* All working

* add docker compose

* update README.md

* pass and print result myfuncs

* do the same with runonnx

* do the same with runonnx

* remove wrong path

* Simplified Makefile

* Modularize refactor (#4)

* Feature/git ci (#5)

* add ci vs develop

* add .a files

* mkdir: Permission denied

* comment action

* comment action

* update main.go imports

* update main.go imports

* update docker to match new imports

* add docker build workflow

* roll back

* add docker build

* fix docker build

* fix docker build

* comment workflow dep

* try

* conditional in docker

* fix ci job name

* update readme

* remove .idea

* Go ORT (#6)

* remmove dep file

* working concept

* working concept 2

* add release funcs

* add wrapper methods

* add wrapper methods

* add wrapper methods

* add wrapper methods

* it works

* remove unused job

* comment job condition

* Enhance ORT (#7)

* Add errors stack trace

* remove .o file

* remove outdated file

* add build to ci