Feature/build docker (#2)
* make onnx module

* need to fix undefined reference to modules

* make file and docker works but image isnt finding the onnxruntime

* All working

* add docker compose

* update README.md

* pass and print result myfuncs

* do the same with runonnx

* do the same with runonnx

* remove wrong path